### ISSUE TITLE
add adjustable # of bins.

### ISSUE THREAD

**Issue by jimnoneill** [juanvillada/CodG#1]
In both 2.CodG_QuantiCUB.R and 3.CodG_ExVar3D.R I can't seem to change the number of bins from 10 to any number without an error. 
For example from 3.CodG_ExVar3D.R I get the following when I set the # of bins to 30:

Wait... analysing the Genome # 1 of 100
Error: subscript contains out-of-bounds indices
Called from: .subscript_error("subscript contains out-of-bounds indices")

Otherwise, a great tool for codon analysis. :)

**Comment by juanvillada** [comment]
Hi @jimnoneill 

I'm really sorry, I never got a notification about this issue. Are you still interested in using `CodG`?

I can spare some time to revise the issue and give a global update to the code if you need to use it.

Best!
